const data = {
  "currentDate": "2026-01-01",
  "events": [
    {
      _id: 1,
      "image":  "https://radio.unr.edu.ar/wp-content/uploads/2024/09/colectividades-DEF-1-1.jpg",
      "name": "Fiesta de las Colectividades",
      "date": "2025-12-12",
      "description": "Disfrutá de tus platos favoritos de diferentes países en un evento único para toda la familia.",
      "descriptionxx": "Un recorrido cultural y gastronómico que reúne stands culinarios de más de 30 países. Además de la oferta de platos típicos y postres tradicionales, el festival cuenta con dos escenarios principales donde se presentan danzas folclóricas, música en vivo y talleres de cocina interactivos para toda la familia durante todo el fin de semana.",
      "category": "Gastronomia",
      "place": "Salón A",
      "capacity": 45000,
      "assistance": 42756,
      "price": 6000
    },
    {
      _id: 2,
      "image": "https://imag.bonviveur.com/corea.jpg",
      "name": "Estilo Coreano",
      "date": "2025-08-12",
      "description": "Disfrutá de los mejores platos coreanos con chefs internacionales y eventos espectaculares.",
      "descriptionxx": "La feria definitiva para los amantes de la cultura asiática y el K-Food. Este año contamos con masterclasses dictadas por chefs estrellas Michelin llegados directamente de Seúl, zonas exclusivas para degustación de barbacoa coreana, concursos de cocina rápida para aficionados y un sector dedicado a la venta de ingredientes importados difíciles de conseguir.",
      "category": "Gastronomia",
      "place": "Salón A",
      "capacity": 45000,
      "assistance": 42756,
      "price": 12000
    },
    {
      _id: 3,
      "image":  "https://cosasdebarrioweb.com.ar/wp-content/uploads/2025/07/Museo.jpg",
      "name": "Parque Jurásico",
      "date": "2025-11-02",
      "description": "Vení a conocer a los dinosaurios más grandes en el museo de paleontología.",
      "descriptionxx": "Una impactante exhibición paleontológica al aire libre que incluye más de 25 réplicas de dinosaurios animatrónicos a escala real con sonido y movement autónomo. La propuesta se complementa con zonas de excavación simuladas para que los niños jueguen a ser científicos, proyecciones en 3D sobre la era mesozoica y charlas guiadas por expertos del museo.",
      "category": "Cultura y Arte",
      "place": "Predio al aire libre",
      "capacity": 82000,
      "assistance": 65892,
      "price": 18000
    },
    {
      _id: 4,
      "image": "https://www.franciaturismo.net/es/wp-content/uploads/sites/17/paris-louvre-piramide-hd.jpg",
      "name": "Museo Parisino",
      "date": "2025-11-02",
      "description": "Un recorrido único en la ciudad de las luces, vení a conocer uno de los lugares más icónicos.",
      "descriptionxx": "Una muestra artística internacional que traslada la magia de los museos de París a través de galerías físicas e instalaciones digitales avanzadas. Los visitantes podrán apreciar reproducciones certificadas de alta fidelidad de obras maestras del Louvre y el Museo de Orsay, acompañadas por una audioguía interactiva descargable en el teléfono celular.",
      "category": "Cultura y Arte",
      "place": "París",
      "capacity": 8200,
      "assistance": 8200,
      "price": 45000
    },
    {
      _id: 5,
      "image": "https://offloadmedia.feverup.com/secretnyc.co/wp-content/uploads/2023/09/07204734/Comic-Con-NY.shutterstock_1197392752-1024x683.jpg",
      "name": "Comic Con",
      "date": "2025-02-12",
      "description": "Para los fanáticos de los cómics, todos tus personajes favoritos juntos en un solo lugar.",
      "descriptionxx": "La convención de cultura pop e industrias creativas más grande de la región. El cronograma incluye paneles de preguntas y respuestas con actores de Hollywood, callejón de artistas independientes, stands de las principales editoriales de cómics y mangas, desfiles oficiales de cosplay con importantes premios en efectivo y salas de videojuegos de última generación.",
      "category": "Ferias y Festivales",
      "place": "Salón C",
      "capacity": 120000,
      "assistance": 110000,
      "price": 65000
    },
    {
      _id: 6,
      "image": "https://offloadmedia.feverup.com/bairessecreta.com/wp-content/uploads/2023/10/22183336/fiestas-halloween-bruce.jpg",
      "name": "Noche de Halloween",
      "date": "2025-02-12",
      "description": "Vení con tu disfraz más terrorífico y ganá premios increíbles.",
      "descriptionxx": "El festival nocturno temático definitivo de la temporada. Los pabellones del Salón C se transforman por completo en laberintos de terror hiperrealistas con actores en vivo. La noche cierra con una fiesta masiva liderada por reconocidos DJs, un concurso abierto de disfraces en categorías de terror y efectos especiales, y zonas de maquillaje artístico gratuito.",
      "category": "Ferias y Festivales",
      "place": "Salón C",
      "capacity": 12000,
      "assistance": 9000,
      "price": 15000
    },
    {
      _id: 7,
      "image": "https://e01-elmundo.uecdn.es/assets/multimedia/imagenes/2024/07/12/17208198320557.jpg",
      "name": "Metallica en concierto",
      "date": "2025-01-22",
      "description": "El único recital de la banda más emblemática del mundo.",
      "descriptionxx": "El legendario cuarteto de thrash metal regresa con un despliegue escénico descomunal que incluye pantallas LED de 360 grados y un sistema de sonido de última generación. Una cita imperdible para repasar cuatro décadas de éxitos históricos, himnos generacionales y los nuevos cortes de su última producción discográfica en una noche cargada de pura energía.",
      "category": "Musica",
      "place": "Salón A",
      "capacity": 138000,
      "assistance": 138000,
      "price": 180000
    },
    {
      _id: 8,
      "image": "https://disfrutarosario.com/wp-content/uploads/2020/04/Fiestas-electr%C3%B3nicas-en-Argentina-2020.jpg",
      "name": "Fiesta Electrónica",
      "date": "2026-01-22",
      "description": "Los mejores DJs nacionales e internacionales juntos en un solo lugar.",
      "descriptionxx": "Un festival nocturno dedicado por completo a los géneros del techno y house. Cuenta con dos escenarios equipados con tecnología lumínica de vanguardia, lásers de alta definición y efectos especiales visuales. La grilla artística combina leyendas globales de las pistas europeas junto a los talentos emergentes más destacados de la escena electrónica local.",
      "category": "Musica",
      "place": "Salón A",
      "capacity": 138000,
      "estimate": 110300,
      "price": 280000
    },
    {
      _id: 9,
      "image": "https://www.clarin.com/img/2025/04/25/PyImFXHwn_720x0__1.jpg",
      "name": "10K por la Vida",
      "date": "2026-03-01",
      "description": "Vení a hacer ejercicio, mejorá tu salud y tu estilo de vida.",
      "descriptionxx": "Una maratón urbana diseñada tanto para corredores profesionales que buscan romper marcas como para familias completas que desean marchar por una causa saludable. El recorrido urbano está completamente señalizado y cardioprotegido, ofreciendo múltiples puestos de hidratación, kinesiología gratuita post-carrera y una medalla de participación para todos.",
      "category": "Deportes",
      "place": "Cancha de fútbol",
      "capacity": 30000,
      "estimate": 25698,
      "price": 4000
    },
    {
      _id: 10,
      "image":  "https://www.clarin.com/img/2017/11/20/rJANgcegG_312x240.jpg",
      "name": "15K Nueva York",
      "date": "2026-03-01",
      "description": "Vamos a juntar fondos para hospitales y atención médica en este evento único en la Gran Manzana.",
      "descriptionxx": "Una de las competencias benéficas más prestigiosas del circuito internacional de atletismo. El circuito atraviesa los puntos más icónicos de la ciudad de Nueva York, convocando a miles de deportistas internacionales. Todo lo recaudado por inscripciones se destina de forma directa a la optimización de equipamiento médico y fondos de investigación oncológica.",
      "category": "Deportes",
      "place": "Nueva York",
      "capacity": 3000000,
      "estimate": 2569800,
      "price": 4000
    },
    {
      _id: 11,
      "image": "https://thumbs.dreamstime.com/b/libro-antiguo-con-letras-voladoras-y-luz-m%C3%A1gica-sobre-el-fondo-de-la-estanter%C3%ADa-biblioteca-libros-antiguos-como-s%C3%ADmbolo-218640948.jpg",
      "name": "Feria del libro escolar",
      "date": "2026-10-15",
      "description": "Traé los manuales escolares que ya no uses y llevate el que te haga falta.",
      "descriptionxx": "Un gran espacio colaborativo y comunitario diseñado para mitigar los costos del inicio del ciclo lectivo. Los estudiantes y tutores pueden intercambiar textos escolares, novelas educativas y enciclopedias bajo un sistema transparente de puntos. El predio dispone además de talleres abiertos sobre métodos de estudio eficientes y fomento de la lectura juvenil.",
      "category": "Tecnologia y Educación",
      "place": "Salón D1",
      "capacity": 150000,
      "estimate": 123286,
      "price": 1500
    },
    {
      _id: 12,
      "image": "https://pictures.abebooks.com/inventory/9671615806.jpg",
      "name": "Especial para tu cocina",
      "date": "2026-11-09",
      "description": "Si te encanta la gastronomía, vení a buscar el libro de recetas que mejor vaya con tus gustos y los de tu familia.",
      "descriptionxx": "Si te encanta la gastronomía, vení a buscar el libro de recetas que mejor vaya con tus gustos y los de tu familia. Vas a encontrar opciones de cocina internacional, repostería avanzada y menús saludables explicados paso a paso por reconocidos chefs de la región.",
      "category": "Tecnologia y Educación",
      "place": "Salón D6",
      "capacity": 130000,
      "estimate": 90000,
      "price": 120000
    },
    {
      _id: 13,
      "image": "https://static.eldiario.es/clip/9609c323-466f-47d9-b366-08c1f0d94f5c_16-9-aspect-ratio_default_0.jpg",
      "name": "Rock en el Estadio",
      "date": "2026-03-11",
      "description": "Vení a cantar los mejores clásicos del rock nacional e internacional en una noche histórica en Buenos Aires.",
      "descriptionxx": "Un megafestival musical masivo en el mítico Monumental de Núñez. Reunirá sobre un mismo escenario a las bandas de rock más legendarias del país junto a invitados sorpresa internacionales. Contará con patios gastronómicos cerveceros, venta de merchandising oficial exclusivo y un despliegue técnico de luces y sonido inédito en la historia de los conciertos locales.",
      "category": "Musica",
      "place": "Estadio River Plate",
      "capacity": 85000,
      "estimate": 83000,
      "price": 45000
  },
  {
      _id: 14,"image": "https://agencia.unq.edu.ar/wp-content/uploads/2022/02/destacada_Xime07.02.jpg",
      "name": "Van Gogh Inmersivo",
      "date": "2026-10-15",
      "description": "Un viaje multisensorial a través de las obras más famosas del genio del postimpresionismo.",
      "descriptionxx": "Una sofisticada experiencia artística que combina proyecciones digitales en alta definición de piso a techo, tecnologías de realidad virtual de última generación y una banda sonora envolvente compuesta a medida. Los espectadores podrán literalmente caminar por dentro de cuadros eternos como La Noche Estrellada o Los Girasoles.",
      "category": "Cultura y Arte",
      "place": "Salón D1",
      "capacity": 9000,
      "estimate": 9000,
      "price": 10500
  }
]
};