const data = {
    "currentDate": "2026-01-01",
    "events": [
      {
        _id: 1,
        "image":"https://postimg.cc",
        "name":"Fiesta de las Colectividades",
        "date":"2026-12-12",
        "description":"Disfrutá de tus platos favoritos de diferentes países en un evento único para toda la familia.",
        "category":"Feria Gastronómica",
        "place":"Salón A",
        "capacity":45000,
        "assistance":42756,
        "price": 6000
      },
      {
        _id: 2,
        "image":"https://postimg.cc",
        "name":"Estilo Coreano",
        "date":"2025-08-12",
        "description":"Disfrutá de los mejores platos coreanos con chefs internacionales y eventos espectaculares.",
        "category":"Feria Gastronómica",
        "place":"Salón A",
        "capacity":45000,
        "assistance":42756,
        "price": 12000
      },
      {
        _id: 3,
        "image":"https://postimg.cc",
        "name":"Parque Jurásico",
        "date":"2026-11-02",
        "description":"Vení a conocer a los dinosaurios más grandes en el museo de paleontología.",
        "category":"Museo",
        "place":"Predio al aire libre",
        "capacity":82000,
        "assistance":65892,
        "price": 18000
      },
      {
        _id: 4,
        "image":"https://postimg.cc",
        "name":"Museo Parisino",
        "date":"2026-11-02",
        "description":"Un recorrido único en la ciudad de las luces, vení a conocer uno de los lugares más icónicos.",
        "category":"Museo",
        "place":"París",
        "capacity":8200,
        "estimate":8200,
        "price": 45000
      },
      {
        _id: 5,
        "image":"https://postimg.cc",
        "name":"Comic Con",
        "date":"2026-02-12",
        "description":"Para los fanáticos de los cómics, todos tus personajes favoritos juntos en un solo lugar.",
        "category":"Fiesta de Disfraces",
        "place":"Salón C",
        "capacity":120000,
        "assistance":110000,
        "price": 65000
      },
      {
        _id: 6,
        "image":"https://postimg.cc",
        "name":"Noche de Halloween",
        "date":"2026-02-12",
        "description":"Vení con tu disfraz más terrorífico y ganá premios increíbles.",
        "category":"Fiesta de Disfraces",
        "place":"Salón C",
        "capacity":12000,
        "estimate":9000,
        "price": 15000
      },
      {
        _id: 7,
        "image":"https://postimg.cc",
        "name":"Metallica en concierto",
        "date":"2026-01-22",
        "description":"El único recital de la banda más emblemática del mundo.",
        "category":"Recital",
        "place":"Salón A",
        "capacity":138000,
        "estimate":138000,
        "price": 180000
      },
      {
        _id: 8,
        "image":"https://postimg.cc",
        "name":"Fiesta Electrónica",
        "date":"2026-01-22",
        "description":"Los mejores DJs nacionales e internacionales juntos en un solo lugar.",
        "category":"Recital",
        "place":"Salón A",
        "capacity":138000,
        "assistance":110300,
        "price": 280000
      },
      {
        _id: 9,
        "image":"https://postimg.cc",
        "name":"10K por la Vida",
        "date":"2026-03-01",
        "description":"Vení a hacer ejercicio, mejorá tu salud y tu estilo de vida.",
        "category":"Carrera",
        "place":"Cancha de fútbol",
        "capacity":30000,
        "assistance":25698,
        "price": 4000
      },
      {
        _id: 10,
        "image":"https://postimg.cc",
        "name":"15K Nueva York",
        "date":"2026-03-01",
        "description":"Vamos a juntar fondos para hospitales y atención médica en este evento único en la Gran Manzana.",
        "category":"Carrera",
        "place":"Nueva York",
        "capacity":3000000,
        "assistance":2569800,
        "price": 4000
      },
      {
        _id: 11,
        "image":"https://postimg.cc",
        "name":"Feria del libro escolar",
        "date":"2026-10-15",
        "description":"Traé los manuales escolares que ya no uses y llevate el que te haga falta.",
        "category":"Intercambio de Libros",
        "place":"Salón D1",
        "capacity":150000,
        "estimate":123286,
        "price": 1500
      },
      {
        _id: 12,
        "image":"https://postimg.cc",
        "name":"Especial para tu cocina",
        "date":"2026-11-09",
        "description":"Si te encanta la gastronomía, vení a buscar el libro de recetas que mejor vaya con tus gustos y los de tu familia.",
        "category":"Intercambio de Libros",
        "place":"Salón D6",
        "capacity":130000,
        "assistance":90000,
        "price": 120000
      },
      {
        _id: 13,
        "image":"https://postimg.cc",
        "name":"Batman",
        "date":"2026-03-11",
        "description":"Vení a ver a Batman combatir el crimen en Ciudad Gótica.",
        "category":"Cine",
        "place":"Salón D1",
        "capacity":11000,
        "assistance":9300,
        "price": 8500
      },
      {
        _id: 14,
        "image":"https://postimg.cc",
        "name":"Avengers",
        "date":"2026-10-15",
        "description":"Avant premiere en 3D de Avengers de Marvel, el comienzo de una saga épica con tus superhéroes favoritos.",
        "category":"Cine",
        "place":"Salón D1",
        "capacity":9000,
        "estimate":9000,
        "price": 10500
      }
    ]
  };